### PR TITLE
Feature/mailing component and JWT fix

### LINKED ISSUE #12: JWT Filter does not work properly
JWTFilter does not provide the behavior that is desired - authorizes requests but it is hard infer when request does not pass through. Possble issue is in config

### PR DESCRIPTION
**Pull request by Pumbakos**
- Add Mail module -> core module for Newsler app
- Fix JWTFilter issue [closes #12]
- Fix contextLoads() test issue when no enviroment variables were set
- Update README.md

### CODE REVIEW

File: src/main/java/pl/newsler/auth/NLAuthenticationProvider.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+import org.springframework.security.core.AuthenticationException;
+import org.springframework.stereotype.Component;
+import pl.newsler.components.user.IUserRepository;
+import pl.newsler.components.user.NLUser;
+import pl.newsler.security.NLAuthenticationToken;
+import pl.newsler.security.NLPrincipal;
+
+import java.util.Optional;
+
+@Component
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/auth/NLAuthenticationProvider.java]: Should be provided be configuration class

File: src/main/java/pl/newsler/commons/models/NLMessage.java [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+import lombok.NoArgsConstructor;
+import lombok.RequiredArgsConstructor;
+
+import java.io.Serial;
+
+@Getter
+@NoArgsConstructor(access = AccessLevel.PACKAGE, force = true)
+@RequiredArgsConstructor(access = AccessLevel.PUBLIC, staticName = "of")
+@EqualsAndHashCode
+public class NLMessage implements NLModel {
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/commons/models/NLMessage.java]: Rename to `NLEmailMessage`

File: src/main/java/pl/newsler/commons/models/NLStringValue.java [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+
+    public static NLStringValue of(String value) {
+        return new NLStringValue(value);
+    }
+
+    public static NLStringValue of(String[] values) {
+        return of(Arrays.toString(values));
+    }
+
+    private final String value;
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/commons/models/NLStringValue.java:28]: Rearange code

File: src/main/java/pl/newsler/commons/models/NLStringValue.java [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+import java.io.Serial;
+import java.io.Serializable;
+import java.util.Arrays;
+
+@Getter
+@NoArgsConstructor(access = AccessLevel.PACKAGE, force = true)
+@RequiredArgsConstructor(access = AccessLevel.PUBLIC)
+@EqualsAndHashCode
+public class NLStringValue implements Serializable {
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/commons/models/NLStringValue.java]: Consider implementing `NLModel`

File: src/main/java/pl/newsler/components/emaillabs/IMailRepository.java [hunk 5]
```diff
@@ -0,0 +1,9 @@
+package pl.newsler.components.emaillabs;
+
+import pl.newsler.commons.models.NLId;
+
+import java.util.List;
+
+public interface IMailRepository extends MailRepositoryJpa {
+    List<NLUserMail> findAllByUserId(NLId userId);
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/components/emaillabs/IMailRepository.java:9]: Consider adding `Query()` annotation

File: src/main/java/pl/newsler/components/emaillabs/MailModuleConfiguration.java [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+    private final IMailRepository mailRepository;
+    private final NLIPasswordEncoder passwordEncoder;
+
+    @Bean(name = "restTemplate")
+    RestTemplate restTemplate() {
+        return new RestTemplate();
+    }
+
+    @Bean(name = "taskExecutor")
+    ELATaskExecutor taskExecutor(RestTemplate restTemplate) {
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/components/emaillabs/MailModuleConfiguration.java]: Interface for `ELATaskExecutor` ?

File: src/main/java/pl/newsler/components/user/NLUser.java [hunk 7]
```diff
@@ -101,7 +101,7 @@ public class NLUser implements UserDetails {
 
     @Enumerated
     @AttributeOverrides(value = @AttributeOverride(name = "value", column = @Column(name = "ROLE")))
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/components/user/NLUser.java]: Should not be simple `@Column` annotation?

File: src/main/java/pl/newsler/components/user/UserCrudService.java [hunk 8]
```diff
@@ -12,15 +10,15 @@
...
 import java.util.Optional;
 import java.util.UUID;
 
 @RequiredArgsConstructor
 class UserCrudService implements IUserCrudService {
-    private final UserRepository userRepository;
+    private final IUserRepository userRepository;
     private final NLIPasswordEncoder passwordEncoder;
 
     @Override
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/components/user/UserCrudService.java:25]: Annotate param with `@NotNull` from validation package. Use `NLModel.validate()` to chcek its correctness.

File: src/main/java/pl/newsler/security/filters/JWTFilter.java [hunk 9]
```diff
@@ -4,51 +4,87 @@
...
+    private final AuthenticationManager authenticationManager;
+    private final AuthUserDetailService authUserDetailService;
     private final JWTUtility utility;
+    private final String filterNotProcessingUrl;
 
-    public JWTFilter(AuthenticationManager authenticationManager, IUserRepository repository, JWTUtility utility) {
-        super(authenticationManager);
-        this.repository = repository;
+    /**
+     * Creates a new instance with a default filterProcessesUrl and an
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/security/filters/JWTFilter.java:46]: Do not brake the line

File: src/main/java/pl/newsler/security/filters/JWTFilter.java [hunk 10]
```diff
@@ -4,51 +4,87 @@
...
+     * {@link AuthenticationManager}
+     *
+     * @param filterNotProcessingUrl the default value for <tt>filterProcessesUrl</tt>.
+     * @param authenticationManager  the {@link AuthenticationManager} used to authenticate
+     *                               an {@link Authentication} object. Cannot be null.
+     * @param authUserDetailService  {@link org.springframework.security.core.userdetails.UserDetailsService}
+     */
+    public JWTFilter(@NotNull String filterNotProcessingUrl, AuthenticationManager authenticationManager, AuthUserDetailService authUserDetailService, @NotNull JWTUtility utility) {
```
Comment (Pumbakos) [inline src/main/java/pl/newsler/security/filters/JWTFilter.java]: Insert `@NotNull` to all params
